assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:
        - AxiomaBookBundle

    filters:
        cssrewrite: ~

    assets:
        bootstrap_css:
            inputs:
                - "//cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.1.1/css/bootstrap.min.css"
        bootstrap_js:
            inputs:
                - "//cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.1.1/js/bootstrap.min.js"
        jquery:
            inputs:
                - "//ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"
        app_css:
            inputs:
                - "%kernel.root_dir%/Resources/public/css/main.css"