axioma_movie:
    resource: "@AxiomaMovieBundle/Resources/config/routing.yml"
    prefix:   /

axioma_book:
    resource: "@AxiomaBookBundle/Resources/config/routing.yml"
    prefix:   /

homepage:
    pattern:  /
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /books/