parameters:
    axioma.entity.tag.class: Axioma\TagBundle\Entity\Tag
    axioma.manager.tag.class: Axioma\TagBundle\EntityManager\TagManager
    axioma.type.tags_input.class: Axioma\TagBundle\Form\Type\TagsTextInputType

services:
    axioma.type.tags_input:
        class: %axioma.type.tags_input.class%
        arguments: [@doctrine.orm.entity_manager]
        tags:
            - { name: form.type, alias: tags }

    axioma.manager.tag:
        class: %axioma.manager.tag.class%
        arguments:
            - @doctrine.orm.entity_manager
            - %axioma.entity.tag.class%